### PR TITLE
docs(naming conventions): add mindmap

### PR DESCRIPTION
**Pull request by sambacha**
added a mindmap to help viz. this rat nest

### CODE REVIEW

**Comment by sambacha** [comment]
Different mindmap potentially: 

https://www.mermaidchart.com/app/projects/7a5a269a-c4a2-491e-992a-c21152b6e4ce/diagrams/79083b72-292d-4ee4-8cdb-1b53e84fadec/version/v0.1/edit

**Comment by MarcoWorms** [comment]
unfortunately our docs is not rendering mermaid right now, but I will check this and see if I can fix in this PR! tyvm for the PR, I shall come back here by tomorrow

image

**Comment by MarcoWorms** [comment]
hey ser i didnt forget this, we are finishing the docs refactor in the PR below then I'm coming to see the mermaid render to merge this

**Comment by rossgalloway** [comment]
This should work now with the recent update of docusaurus to V3. @sambacha can you sync this PR with the updates to the master branch? Or @MarcoWorms maybe you can do it directly?

**Comment by rossgalloway** [comment]
This PR should be closed as it is replaced by #436

**Pull request closed without merging**
