### PR TITLE
fix: rm grey border when searching, closes #132

### LINKED ISSUE #132: Grey border when searching
There's a grey border when searching and the window is between desktop and mobile. That line shouldn't be there. 

Screenshot 2022-01-12 at 18 07 47

### PR DESCRIPTION
**Pull request by KurogeWashu**

### CODE REVIEW

**Comment by saltyfacu** [comment]
I still see the border. It seems that some components have different media definition and that's why the border appears at a larger size than when the component change.

### Fullscreen
Screenshot 2022-01-17 at 10 45 50

### Smaller screen with grey border
Screenshot 2022-01-17 at 10 46 14

### Mobile version working good
Screenshot 2022-01-17 at 10 46 58

**Comment by KurogeWashu** [comment]
@saltyfacu good catch, fixed it

**Comment by saltyfacu** [comment]
Now the border doesn't appear when it has to, when the search bar moves to the left. Check the image please

Screenshot 2022-01-24 at 18 37 45

**Comment by KurogeWashu** [comment]
@saltyfacu thx for finding the bugs. Pushed new fixes

**Review by saltyfacu — APPROVED** [review]
great job! thanks

**Pull request merged**
