### PR TITLE
Update using-yearn.md

### PR DESCRIPTION
**Pull request by theminion0987**
Updated page with walkthrough screenshots V3 vault. Removed Zapping feature as no longer featured on V3 or V2 vaults.

### CODE REVIEW

**Comment by rossgalloway** [comment]
Hey @theminion0987, I'm going to be taking over docs management for Marco.  I want to have some more complete conversations with you and the rest of ySupport about what you want to see from the docs repo, but I wanted to throw out some thoughts I had as I have been working through ideas and saw your pull request here.

Since the V2 vaults still exist, it seems to me that we would want to have walk-throughs for both the V2 and the V3 vaults. They could be very similar, where we keep what you have here as the V3 walk-through, and then also keep the old V2 version but change the first 2 images to show the new network selection flow and remove the zapping part if that isn't being used anymore. I would also move these 2 walk-throughs into the `Guides` section.

I'm happy to do the heavy lifting on these changes if you (and the ySupport team) think they are a good idea. Looking forward to hearing your thoughts.

**Comment by theminion0987** [comment]
Hey, glad to see you managing the docs. Please let me know if I can support
in any way. Sounds all good regarding the V2/V3 doc changes - I'll speak
through the ySupport team if there is anything they would like to see that
would make things easier and let you know. Thanks for reaching out! (missed
this notification so apologies for the slow response)

**Review by MarcoWorms — APPROVED** [review]

**Comment by MarcoWorms** [comment]
sorry I was reviewing this and accidentally approved (bc no issues found in changes made), but I just saw that ross was talking to you about it here so I will wait for confirmation before merging this!

**Comment by MarcoWorms** [comment]
incuded in #437

**Pull request closed without merging**
