### PR TITLE
Upgrade docusaurus to 2.0.0-beta.21

### PR DESCRIPTION
**Pull request by MarcoWorms**
- upgrades docusaurus from beta.6 to beta.21
- make most sidebars expanded by default so all pages are more explicit to users
- removes unused old homepage code

### CODE REVIEW

**Comment by saltyfacu** [comment]
Great initiative to update docusaurus. A few things to change since we are updating:

- Please disable breadcrumbs
Screenshot 2022-06-21 at 11 12 15

- The background color of the dark mode should be #18191a

- Can you update Yearn's logo to the latest version?

- I'd like to remove the author on the footer. What do you think?

**Comment by MarcoWorms** [comment]
@saltyfacu I agree with removing author from footnotes! will change configs to match this and apply the others requests too, thanks!

**Comment by MarcoWorms** [comment]
@saltyfacu where can I find an SVG version of the updated logo?

**Comment by saltyfacu** [comment]
> @saltyfacu where can I find an SVG version of the updated logo?
Here: [logo](https://user-images.githubusercontent.com/839844/174996166-87ac0f03-2bef-40fa-9047-8cd11cf2be88.svg)

**Comment by MarcoWorms** [comment]
all review points applied!

**Pull request merged**
