### PR TITLE
[DOC-45] Feat/add partner docs

### PR DESCRIPTION
**Pull request by fameal**

### CODE REVIEW

**Comment by lehnberg** [comment]
Looks great content wise, but I caught a typo, have you run this through a spell and grammar checker? 👀

**Comment by fameal** [comment]
> Looks great content-wise, but I caught a typo, have you run this through a spell and grammar checker? 👀

Good suggestion. I have to get used to run Grammarly on all the docs. 

- I've fixed several typos
- Also changed some stuff, grammar-related, based on Grammarly suggestions

Please check it out again.

**Comment by philburrrt** [comment]
I made my edits here. https://github.com/yearn/yearn-devdocs/pull/19

**Comment by fameal** [comment]
Superseded by #19

**Comment by fameal** [comment]
@lehnberg I cloed the PR by mistake. Would you review this please?

**Review by lehnberg — APPROVED** [review]
LGTM

**Pull request merged**
